import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./NavBar";
import { PlaybackBar } from "./PlaybackBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="pb-4">{children}</div>
        <div className="fixed top-0 left-0 right-0">
          <NavBar />
        </div>
        <div className="fixed h-24 bg-base-100 bottom-0 left-0 right-0 inset-shadow-sm">
          <PlaybackBar />
        </div>
      </body>
    </html>
  );
}
